# Generated by Django 2.0 on 2018-07-18 17:54

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=redactor.fields.RedactorField(verbose_name='Yogesh'),
        ),
    ]
